fix: production yml conflict

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -3,8 +3,8 @@ on:
   pull_request:
     branches: ['production']
 jobs:
-  production:
-    runs-on: ['self-hosted', 'production']
+  build:
+    runs-on: ["self-hosted", "ubuntu"]
     strategy:
       matrix:
         node-version: [20.x]
@@ -25,7 +25,51 @@ jobs:
         run: npm run build --if-present
       - name: Run migrations
         run: npx medusa migrations run
-      - name: Deploy to production pm2
+      - name: Archive production artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: dist
+          path: |
+            dist
+            .env
+            package.json
+            package-lock.json
+
+  deploy:
+    runs-on: ["self-hosted", "ubuntu"]
+    needs: [build]
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+      - name: List contents of current directory
+        run: ls -la
+      - name: Copy files to Production
+        run: |
+          # Ensure the deployment directory exists
+          mkdir -p ~/dob-server
+
+          # Copy new files to the deployment directory
+          cp -R dist/* ~/dob-server/ || echo "No dist directory found"
+          cp .env ~/dob-server/ || echo "No .env file found"
+          cp package.json ~/dob-server/ || echo "No package.json found"
+          cp package-lock.json ~/dob-server/ || echo "No package-lock.json found"
+
+          # Navigate to the deployment directory
+          cd ~/dob-server
+      - name: Install dependencies for Production deployment
+        run: |
+          sleep 10  # Adjust this value based on your application's startup time
+          cd ~/dob-server
+          echo "Current directory: $(pwd)"
+          echo "PATH: $PATH"
+          echo "Current user: $(whoami)"
+          echo "NVM_DIR: $NVM_DIR"
+          which node || echo "node not found in PATH"
+          which npm || echo "npm not found in PATH"
+          npm ci
+      - name: Deploy to Production pm2
         run: |
           # Restart or start the PM2 process
           if pm2 list | grep -q "backend"; then
