fix: change name action for env staging, production

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -4,7 +4,7 @@ on:
     branches: ['production']
 jobs:
   build:
-    runs-on: production
+    runs-on: ['self-hosted', 'ubuntu']
     strategy:
       matrix:
         node-version: [20.x]
@@ -36,7 +36,7 @@ jobs:
             package-lock.json
 
   deploy:
-    runs-on: production
+    runs-on: ['self-hosted', 'ubuntu']
     needs: [build]
     steps:
       - name: Download artifact
@@ -45,7 +45,7 @@ jobs:
           name: dist
       - name: List contents of current directory
         run: ls -la
-      - name: Copy files to staging
+      - name: Copy files to production
         run: |
           # Ensure the deployment directory exists
           mkdir -p ~/dob-server
@@ -58,9 +58,27 @@ jobs:
 
           # Navigate to the deployment directory
           cd ~/dob-server
-      - name: Install dependencies for staging deployment
-        run: npm ci
-      - name: Deploy to staging pm2
+      # - name: Install dependencies for production deployment
+      #   run: npm ci
+      - name: Install dependencies for production deployment
+        run: |
+          # Restart or start the PM2 process
+          sleep 10	# Adjust this value based on your application's startup time
+          echo "Current user: $(whoami)"
+          echo "Current directory: $(pwd)"
+          echo "PATH: $PATH"
+          echo "NVM_DIR: $NVM_DIR"
+          which node || echo "node not found in PATH"
+          which npm || echo "npm not found in PATH"
+          su dobtech
+          echo "Current user: $(whoami)"
+          echo "Current directory: $(pwd)"
+          echo "PATH: $PATH"
+          echo "NVM_DIR: $NVM_DIR"
+          which node || echo "node not found in PATH"
+          which npm || echo "npm not found in PATH"
+          npm ci
+      - name: Deploy to production pm2
         run: |
           # Restart or start the PM2 process
           if pm2 list | grep -q "backend"; then
